# Generated by Django 4.2 on 2026-06-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Image ka naam ya caption (Optional)', max_length=100)),
                ('image', models.ImageField(help_text='Premium quality image upload karein', upload_to='cafe_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cafe Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
