# Generated by Django 4.2 on 2026-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer ka naam', max_length=100)),
                ('email', models.EmailField(help_text='Customer ka email address', max_length=254)),
                ('phone', models.CharField(help_text='Customer ka phone number', max_length=15)),
                ('message', models.TextField(help_text='Customer ka message ya query')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Kab submit hua')),
            ],
            options={
                'verbose_name_plural': 'Cafe Contact Queries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
